// Pull the Phosphor icons the app uses into a small TS module (duotone + bold paths),
// and render the native tab bar PNGs, which only accept raster images.
// Requires `inkscape` on PATH for the PNG step.
const { execFileSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const pkg = path.join(root, 'node_modules', '@phosphor-icons', 'core');
const assets = path.join(pkg, 'assets');
const version = JSON.parse(fs.readFileSync(path.join(pkg, 'package.json'), 'utf8')).version;

// App name -> Phosphor name (https://phosphoricons.com)
const ICONS = {
  add: 'plus',
  addPhoto: 'camera-plus',
  back: 'arrow-left',
  buddy: 'smiley-wink',
  bus: 'bus',
  chat: 'chats-teardrop',
  close: 'x',
  cloud: 'cloud',
  collapse: 'caret-down',
  copy: 'copy',
  download: 'download-simple',
  drizzle: 'drop',
  fit: 'corners-out',
  flight: 'airplane-tilt',
  fog: 'cloud-fog',
  footprints: 'footprints',
  journal: 'book-open-text',
  map: 'map-trifold',
  more: 'dots-three-outline-vertical',
  next: 'caret-right',
  note: 'note-pencil',
  photos: 'images',
  pin: 'map-pin',
  rain: 'cloud-rain',
  send: 'paper-plane-tilt',
  settings: 'gear-six',
  share: 'share-fat',
  shower: 'umbrella',
  snow: 'snowflake',
  snowShower: 'cloud-snow',
  sparkle: 'sparkle',
  speaker: 'speaker-high',
  speakerOff: 'speaker-slash',
  storm: 'cloud-lightning',
  suitcase: 'suitcase-rolling',
  sun: 'sun',
  sunCloud: 'cloud-sun',
  walk: 'person-simple-walk',
  warning: 'warning',
  web: 'globe-hemisphere-east',
};

// Tab icons: outline when idle, duotone when selected
const TABS = { trips: 'suitcase', footprint: 'footprints', settings: 'settings' };

const read = (weight, name) => fs.readFileSync(path.join(assets, weight, `${name}-${weight}.svg`), 'utf8');
const paths = (svg) => [...svg.matchAll(/<path d="([^"]+)"( opacity="[^"]+")?\/>/g)].map((m) => ({ d: m[1], duo: !!m[2] }));

const data = {};
for (const [key, name] of Object.entries(ICONS)) {
  const duotone = paths(read('duotone', name));
  const bold = paths(read('bold', name));
  if (duotone.length !== 2 || !duotone[0].duo || bold.length !== 1) throw new Error(`Unexpected SVG shape for ${name}`);
  data[key] = { duo: duotone[0].d, line: duotone[1].d, bold: bold[0].d };
}

const out = `// Generated by scripts/gen-icons.js from @phosphor-icons/core@${version} (MIT); do not edit
export type IconPaths = { duo: string; line: string; bold: string };
export const ICON_PATHS = ${JSON.stringify(data, null, 2)} satisfies Record<string, IconPaths>;
export type IconName = keyof typeof ICON_PATHS;
`;
fs.writeFileSync(path.join(root, 'src', 'components', 'common', 'icons.ts'), out);
console.log(`icons.ts written (${Object.keys(data).length} icons, ${(out.length / 1024).toFixed(0)} KB)`);

// White template images; the tab bar tints them, keeping the duotone layer's alpha
const tabDir = path.join(root, 'assets', 'images', 'tabs');
const tmp = fs.mkdtempSync(path.join(require('os').tmpdir(), 'tabicons-'));
fs.mkdirSync(tabDir, { recursive: true });
for (const [tab, key] of Object.entries(TABS)) {
  const { duo, line } = data[key];
  const variants = {
    [tab]: `<path d="${line}"/>`,
    [`${tab}-selected`]: `<path d="${duo}" opacity="0.35"/><path d="${line}"/>`,
  };
  for (const [file, body] of Object.entries(variants)) {
    const svg = path.join(tmp, `${file}.svg`);
    fs.writeFileSync(svg, `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="#FFFFFF">${body}</svg>`);
    for (const [suffix, px] of [['', 24], ['@2x', 48], ['@3x', 72]]) {
      execFileSync('inkscape', [svg, '--export-type=png', `--export-filename=${path.join(tabDir, `${file}${suffix}.png`)}`, `-w`, `${px}`, `-h`, `${px}`], { stdio: 'ignore' });
    }
  }
}
fs.rmSync(tmp, { recursive: true });
console.log(`tab icons written to assets/images/tabs`);
