// Inline Leaflet into a TS module so the map WebView needs no CDN (unreliable in mainland China)
const fs = require('fs');
const path = require('path');

const dist = path.join(__dirname, '..', 'node_modules', 'leaflet', 'dist');
const js = fs.readFileSync(path.join(dist, 'leaflet.js'), 'utf8');
const css = fs.readFileSync(path.join(dist, 'leaflet.css'), 'utf8');
const version = require('leaflet/package.json').version;
const out = `// Generated by scripts/gen-leaflet.js from leaflet@${version}; do not edit
export const LEAFLET_JS = ${JSON.stringify(js)};
export const LEAFLET_CSS = ${JSON.stringify(css)};
`;
fs.writeFileSync(path.join(__dirname, '..', 'src', 'map', 'leafletAssets.ts'), out);
console.log(`leafletAssets.ts written (${(out.length / 1024).toFixed(0)} KB)`);
